version: '3.8'

networks:
  iot-network:
    driver: bridge

services:
  # 1. MQTT Broker (Mosquitto)
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883" # Port default MQTT
      - "9001:9001" # Port WebSockets (opsional)
    volumes:
      # Menggunakan konfigurasi default untuk Mosquitto (anonim)
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    networks:
      - iot-network
